SELECT 
    COALESCE(l.MDR_NUMBER, m.MDR_NUMBER) AS MDR_NUMBER,
    l.LOT_ID,
    e.AFFECTED_LOT_LIST,
    m.ASSEMBLY_LOT,
    m.MDR_TITLE,
    m.MDR_DESCRIPTION,

    -- Extract the best available LOT_NUMBER from multiple sources
    CASE
        WHEN REGEXP_SUBSTR(l.LOT_ID, '[A-Z]{4}[A-Z0-9]{8}') IS NOT NULL THEN l.LOT_ID
        WHEN REGEXP_SUBSTR(e.AFFECTED_LOT_LIST, '[A-Z]{4}[A-Z0-9]{8}') IS NOT NULL THEN e.AFFECTED_LOT_LIST
        WHEN REGEXP_SUBSTR(m.ASSEMBLY_LOT, '[A-Z]{4}[A-Z0-9]{8}') IS NOT NULL THEN m.ASSEMBLY_LOT
        WHEN REGEXP_SUBSTR(m.MDR_TITLE, '[A-Z]{4}[A-Z0-9]{8}') IS NOT NULL THEN m.MDR_TITLE
        WHEN REGEXP_SUBSTR(m.MDR_DESCRIPTION, '[A-Z]{4}[A-Z0-9]{8}') IS NOT NULL THEN m.MDR_DESCRIPTION
        ELSE NULL
    END AS LOT_NUMBER,

    l.DEVICE_NAME AS DEVICE_NAME,
    m.MDR_STATUS,
    m.MDR_LEVEL,
    m.FACTORY_NAME,
    m.FACTORY_TYPE_NAME,
    m.MDR_CREATE_DATETIME,
    m.INSERT_DATETIME AS MDR_MODIFY_DATE

FROM 
    qa_data.MDR_LOT l
FULL OUTER JOIN qa_data.MDR m ON l.MDR_NUMBER = m.MDR_NUMBER
FULL OUTER JOIN qa_data.EVENT e ON m.EVENT_NUMBER = e.EVENT_NUMBER

WHERE 
    m.FACTORY_TYPE_NAME = 'Final Manufacturing'
    AND EXTRACT(YEAR FROM m.MDR_CREATE_DATETIME) BETWEEN EXTRACT(YEAR FROM CURRENT_DATE) - 5 AND EXTRACT(YEAR FROM CURRENT_DATE)

ORDER BY 
    m.MDR_CREATE_DATETIME DESC;